### ISSUE TITLE
linux output is not the same as windows

### ISSUE THREAD

**Issue by kicchip** [cgarciagl/goldparser-Lazarus#1]
I experimented with goldparser-lazarus and noticed the linux output is different to windows output. In windows the grammer result is Ok, whereas with linux it stops short of giving a positive result.

**Comment by cgarciagl** [comment]
I'm glad to hear that you are testing this components :+1: 

Can you provide the test case for this issue?, i'm on a mac, so maybe i could figure it out something.

**Comment by kicchip** [comment]
Hi Carlos

I have looked a bit further and I think the problem is related to how gold parser units handle ASCII characters, specifically #10.

To get it working on linux I stripped out #10 like this..

  my_string := Memo1.Text ;  
  my_string := StringReplace( #10 , my_string , '', [rfReplaceAll] ) ;

  gp.OpenTextString( my_string ) ;

If you don't strip out the #10 you get lexical errors every time you try to parse text consisting of multiple lines.

Hope this helps, 
Michael

Date: Wed, 20 Aug 2014 07:41:05 -0700

**Comment by cgarciagl** [comment]
@teo-tsirpanis have provided a fix for this issue
